env:
  global:
    - secure: "TuXkypbtZ+hUa+2ktXbAJUtfzm5B1nuGMF7bTSkyjqVQUoljxvY5DMmkvYkvP7ZIG9TtHq/VVfeo1mrGamA8NdRo3Dk24Ggebc5JbzJrrux+jzLDXl7hb2eNoY/ZeQSVMWqIEsJoxBpbfZ9HLFH0EjsxlrQXD0zYzVKTj4J7y/W1G2hhmEy8gJjEoMeGfDrT3LPueyv3u/QvYwXzU42KSEcV4Nd035hYxiBKvE2tee39UjSNlR5fyanRJtOXOKhJVadqBEAWeJ17IUdEkb+omv9dJUIlzDz0q/D9XcR+cJJzfRP8w3bdW2JuICwZ1NGirxn/tM/bnlzVrn90Ut3z88Z7FrX36jIPJ7Zz3wVItAo36aoGnYxV5tP4k1RuVXL8o7kzKhr96VqrTDDJs5rs9+I+U8AL6T5AUfWMZNiouBx056HlvcKzWr2YUn7f1LD3fPtVN6xHvIUuGfAg7i6ANAftFX40Kp9apo5Tz4qYmgxfa6BbP50F/zGlE6cqbwzElqk9IfVTyL7HWliGhXXQPnfqnFfcyLfjayQn6qNQ25CdpSyv/iCz7d3tqPNWt9V+iuNa4twqXcXFU2bpkLHzjw9PHGSRtpYG/oKEHZWqVGx71fMZVysUxGxYWQMtiVRuZv5X/tL1RvGYiGiSNMYGezCAY1IjEGJu+gfYOHtkHhY="
    - secure: "VM/r48bUR02V1ylKjhC+kWax3mIdDtsQBaaTjSWUuhYCOFKZpcJSqrOZVQb43XSz5ss7aD/F9Xkl+jrffgHeXVxE63UlGf9CbIw+v5s8bJlakDNU2/DEMahyq1ySzj/6An6/a4GA5E3ltNftWIw9PymM+8IgeT+l76DOAU3BbjNhy5wcXHcKWH3uwrlMzLuw9LGcqZaYFwcDHzGcjN13OrO6mQxlbrt+mJQPfcI1Kv29/5XRJeOUG6RV+fbQk27CVkqNTW1GENFOdzvuYX0HETiUw6sjwjsezlnCcBzIDDMJSHpPYp58nUvmfyBCHfB2GXK8hgNoBt7NLIayDyNomgrajiTinRpV8gdP4vkWARY4Zq4+H90pFIsUg3Zk+JQ5YPGySMrdhE3PDy/sBZqMEK2n66kMbfW2qNtOVMBFniW549JVQswWiuTUKd/DFV7z1M4ENakz1n3Zjmtwz+AhVNoiRrAcy4othZKXqpzTAjEnxni9be0qvi/lb2+0l/PxYn4auyyocSnUt8T8N6ekYoQ3Q5Tw6HdyiKpMo7W9rziIpd84hYNkbzMtTNx0nEeyEjuma4iSz6onaPv9hIYwn0iejlcGH+ApFTxleHjyMa6NWG2fu0G0qMsJY4BJpZYYYjnZ9qokpYlLa+pHShy23ga7cNBjnYpeLW0YTta6muw="
    - secure: "PBzo4fc/5ihbc1QuwuhzmCCKvi0/8ZTRPpjCO+YEUOZb8+XnVTUnzTpeRX7FyGMnt7DlDhn1vja+1dy4qL3T6vriZwF+j8ONrK/1EYDPgIrlQOxaMRvx/7+quhzfePJaExY7mwjFkzqts6wLTWLJMF7mNgXrqO7V5KG+3tI724Rj+0egNjFHOvM5wkHjVAYWCVpFxxdCCDSOnf+rf+rjLMZPMJJOq2n+jVJPCLm+fSGLInohRIplKTr9eYBxO4o9k7ILw9bG/RWJawTVYxGEt16IGmvgLcQdMRnMC11Az8ZcZI78zGNR+IBt0txIHQ4kkcdsWlfMOPchL7xeuGttR9fC+Lk4qQEo/mltH6DsSdpK05hiEajeFuZ7cPefLgrYYeMeA6P+yBPAwrLPuH85aXcplH5IsBbqYHWJYGwvaBixoPkndE0tdWQ3Rwu8oSMQG5AEu11ejqhGpf0fabVRLiSILHumwWVqREW7taYInXCUPpp9rsFR5JIBH8AG96d5NlX3LOFxZgnieZD1SocHM4/prqef8G6MnVD7TNEhlTHMFl1JUqYNINActwsROi1P6/uLJ3jqAVa4pdYcGLmJpiccmL0cT6VSRakZPKsRdRL6Er8g1mJYq6Bco5OmVemsuvONrqzW/eMcu4rq+mRx69tS0zrTaLmq0B9o9I4kc1c="
    - COMMIT=${TRAVIS_COMMIT::8}

language: python

sudo: true

python:

- 3.6

install:
  - cp ./requirements.txt ./deps/
  - bash ./deps/installPythonLibs.sh

script:
  - python ./test.py

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=govanguard/legion
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push govanguard/legion
